"""Export Fanora demo data from a source database to a portable SQL file."""

import argparse
import json
import os
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from sqlalchemy import Table, select
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine
from sqlmodel import SQLModel

import app.models.database  # noqa: F401
from app.core.config import settings

DEFAULT_OUTPUT = "fanora_demo_data.sql"

EXPORT_TABLES = [
    "users",
    "user_profiles",
    "wallets",
    "auth_identities",
    "user_roles",
    "user_sessions",
    "login_challenges",
    "auth_security_events",
    "communities",
    "community_members",
    "nft_metadata_versions",
    "chain_operations",
    "collectible_token_types",
    "nft_applications",
    "membership_identity_nfts",
    "collectible_ownerships",
    "community_posts",
    "community_replies",
    "community_post_reactions",
    "community_reply_likes",
    "fan_tasks",
    "task_participations",
    "task_audit_logs",
    "task_content_reviews",
    "daily_check_ins",
    "fan_token_ledger",
    "official_membership_payments",
    "nft_creation_reactions",
    "task_nft_rewards",
    "fan_profile_runs",
]


def async_database_url(url: str) -> str:
    if url.startswith("postgres://"):
        return url.replace("postgres://", "postgresql+psycopg://", 1)
    if url.startswith("postgresql://"):
        return url.replace("postgresql://", "postgresql+psycopg://", 1)
    if url.startswith("sqlite://") and not url.startswith("sqlite+aiosqlite://"):
        return url.replace("sqlite://", "sqlite+aiosqlite://", 1)
    return url


def create_engine(url: str) -> AsyncEngine:
    normalized_url = async_database_url(url)
    options = (
        {}
        if normalized_url.startswith("sqlite")
        else {"pool_pre_ping": True, "connect_args": {"connect_timeout": 30}}
    )
    return create_async_engine(normalized_url, **options)


def sql_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int | float | Decimal):
        return str(value)
    if isinstance(value, datetime):
        return "'" + value.isoformat().replace("'", "''") + "'"
    if isinstance(value, date):
        return "'" + value.isoformat().replace("'", "''") + "'"
    if isinstance(value, dict | list):
        return "'" + json.dumps(value, ensure_ascii=False).replace("'", "''") + "'"
    return "'" + str(value).replace("'", "''") + "'"


def upsert_statement(table: Table, row: dict[str, Any]) -> str:
    columns = [column.name for column in table.columns]
    column_sql = ", ".join(sql_identifier(column) for column in columns)
    value_sql = ", ".join(sql_literal(row[column]) for column in columns)
    primary_keys = [column.name for column in table.primary_key.columns]
    if not primary_keys:
        return f"INSERT INTO {sql_identifier(table.name)} ({column_sql}) VALUES ({value_sql});"

    conflict_sql = ", ".join(sql_identifier(column) for column in primary_keys)
    update_columns = [column for column in columns if column not in primary_keys]
    if not update_columns:
        return (
            f"INSERT INTO {sql_identifier(table.name)} ({column_sql}) VALUES ({value_sql}) "
            f"ON CONFLICT ({conflict_sql}) DO NOTHING;"
        )

    update_sql = ", ".join(f"{sql_identifier(column)} = EXCLUDED.{sql_identifier(column)}" for column in update_columns)
    return (
        f"INSERT INTO {sql_identifier(table.name)} ({column_sql}) VALUES ({value_sql}) "
        f"ON CONFLICT ({conflict_sql}) DO UPDATE SET {update_sql};"
    )


async def export_sql(database_url: str, output_path: Path) -> None:
    engine = create_engine(database_url)
    metadata = SQLModel.metadata
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with output_path.open("w", encoding="utf-8") as file:
            file.write("-- Fanora demo data export. Generated by scripts/export_demo_data_sql.py\n")
            file.write("-- Import with scripts/import_demo_data_sql.py inside Railway.\n\n")
            async with engine.connect() as connection:
                for table_name in EXPORT_TABLES:
                    table = metadata.tables.get(table_name)
                    if table is None:
                        print(f"Warning: skipped unknown table {table_name}")
                        continue
                    rows = (await connection.execute(select(table))).mappings().all()
                    file.write(f"-- table: {table_name}, rows: {len(rows)}\n")
                    for row in rows:
                        file.write(upsert_statement(table, dict(row)))
                        file.write("\n")
                    file.write("\n")
                    print(f"Exported {table_name}: {len(rows)} rows")
    finally:
        await engine.dispose()
    print(f"SQL export written: {output_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-database-url",
        default=os.getenv("SOURCE_DATABASE_URL") or settings.database_url,
        help="Source database URL, defaults to SOURCE_DATABASE_URL or DATABASE_URL",
    )
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help=f"Output SQL file, default: {DEFAULT_OUTPUT}")
    return parser.parse_args()


if __name__ == "__main__":
    import asyncio

    args = parse_args()
    asyncio.run(export_sql(args.source_database_url, Path(args.output)))
