"""Export every database table except alembic_version to a portable SQL file."""

import argparse
import json
import math
import os
import sys
from datetime import date, datetime, time
from decimal import Decimal
from pathlib import Path
from typing import Any

from sqlalchemy import MetaData, Table, select
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

from app.core.config import settings  # noqa: E402

DEFAULT_OUTPUT = BACKEND_ROOT / "fanora_demo_data.sql"
EXCLUDED_TABLES = {"alembic_version"}


def async_database_url(url: str) -> str:
    if url.startswith("postgres://"):
        return url.replace("postgres://", "postgresql+psycopg://", 1)
    if url.startswith("postgresql://"):
        return url.replace("postgresql://", "postgresql+psycopg://", 1)
    if url.startswith("sqlite://") and not url.startswith("sqlite+aiosqlite://"):
        return url.replace("sqlite://", "sqlite+aiosqlite://", 1)
    return url


def create_engine(url: str) -> AsyncEngine:
    normalized_url = async_database_url(url)
    options = (
        {} if normalized_url.startswith("sqlite") else {"pool_pre_ping": True, "connect_args": {"connect_timeout": 30}}
    )
    return create_async_engine(normalized_url, **options)


def sql_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def sql_literal(value: Any, *, dialect_name: str) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int | Decimal):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            return "NULL"
        return repr(value)
    if isinstance(value, datetime | date | time):
        return "'" + value.isoformat().replace("'", "''") + "'"
    if isinstance(value, bytes | bytearray | memoryview):
        hex_value = bytes(value).hex()
        if dialect_name == "postgresql":
            return f"decode('{hex_value}', 'hex')"
        return f"X'{hex_value}'"
    if isinstance(value, dict | list | tuple):
        value = json.dumps(value, ensure_ascii=False, separators=(",", ":"), default=str)
    return "'" + str(value).replace("'", "''") + "'"


def insert_statement(table: Table, row: dict[str, Any], *, dialect_name: str) -> str:
    columns = [column.name for column in table.columns]
    column_sql = ", ".join(sql_identifier(column) for column in columns)
    value_sql = ", ".join(sql_literal(row[column], dialect_name=dialect_name) for column in columns)
    return f"INSERT INTO {sql_identifier(table.name)} ({column_sql}) VALUES ({value_sql});"


async def reflect_tables(engine: AsyncEngine) -> list[Table]:
    metadata = MetaData()
    async with engine.connect() as connection:
        await connection.run_sync(metadata.reflect)
    return [table for table in metadata.sorted_tables if table.name not in EXCLUDED_TABLES]


async def export_sql(database_url: str, output_path: Path) -> None:
    engine = create_engine(database_url)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        tables = await reflect_tables(engine)
        dialect_name = engine.dialect.name
        total_rows = 0
        with output_path.open("w", encoding="utf-8") as file:
            file.write("-- Fanora full data export. Generated by scripts/export_demo_data_sql.py\n")
            file.write("-- Contains every reflected table except alembic_version.\n")
            file.write("-- Restore with scripts/import_demo_data_sql.py.\n\n")
            async with engine.connect() as connection:
                for table in tables:
                    rows = (await connection.execute(select(table))).mappings().all()
                    file.write(f"-- table: {table.name}, rows: {len(rows)}\n")
                    for row in rows:
                        file.write(insert_statement(table, dict(row), dialect_name=dialect_name))
                        file.write("\n")
                    file.write("\n")
                    total_rows += len(rows)
                    print(f"Exported {table.name}: {len(rows)} rows")
    finally:
        await engine.dispose()
    print(f"SQL export written: {output_path} (tables={len(tables)}, rows={total_rows})")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-database-url",
        default=os.getenv("SOURCE_DATABASE_URL") or settings.database_url,
        help="Source database URL, defaults to SOURCE_DATABASE_URL or DATABASE_URL",
    )
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help=f"Output SQL file, default: {DEFAULT_OUTPUT}")
    return parser.parse_args()


if __name__ == "__main__":
    import asyncio

    args = parse_args()
    asyncio.run(export_sql(args.source_database_url, Path(args.output)))
