"""Truncate Fanora demo tables and import SQL generated by export_demo_data_sql.py."""

import argparse
import asyncio
import os
from pathlib import Path

from sqlalchemy import text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

from app.core.config import settings

DEFAULT_INPUT = "fanora_demo_data.sql"

TRUNCATE_TABLES = [
    "task_nft_rewards",
    "nft_creation_reactions",
    "official_membership_payments",
    "fan_token_ledger",
    "daily_check_ins",
    "task_content_reviews",
    "task_audit_logs",
    "task_participations",
    "fan_tasks",
    "community_reply_likes",
    "community_post_reactions",
    "community_replies",
    "community_posts",
    "collectible_ownerships",
    "membership_identity_nfts",
    "nft_applications",
    "collectible_token_types",
    "chain_operations",
    "nft_metadata_versions",
    "community_members",
    "communities",
    "fan_profile_runs",
    "auth_security_events",
    "login_challenges",
    "user_sessions",
    "user_roles",
    "auth_identities",
    "wallets",
    "user_profiles",
    "users",
]


def async_database_url(url: str) -> str:
    if url.startswith("postgres://"):
        return url.replace("postgres://", "postgresql+psycopg://", 1)
    if url.startswith("postgresql://"):
        return url.replace("postgresql://", "postgresql+psycopg://", 1)
    return url


def create_engine(url: str) -> AsyncEngine:
    normalized_url = async_database_url(url)
    options = (
        {}
        if normalized_url.startswith("sqlite")
        else {"pool_pre_ping": True, "connect_args": {"connect_timeout": 30}}
    )
    return create_async_engine(normalized_url, **options)


def split_sql_statements(sql: str) -> list[str]:
    statements: list[str] = []
    current: list[str] = []
    in_quote = False
    index = 0
    while index < len(sql):
        char = sql[index]
        current.append(char)
        if char == "'":
            if in_quote and index + 1 < len(sql) and sql[index + 1] == "'":
                current.append(sql[index + 1])
                index += 2
                continue
            in_quote = not in_quote
        elif char == ";" and not in_quote:
            statement = "".join(current).strip()
            if statement and not statement.startswith("--"):
                statements.append(statement)
            current = []
        index += 1
    tail = "".join(current).strip()
    if tail and not tail.startswith("--"):
        statements.append(tail)
    return statements


async def import_sql(
    database_url: str,
    input_path: Path,
    *,
    truncate: bool,
    continue_on_error: bool,
) -> None:
    if not input_path.exists():
        raise FileNotFoundError(f"SQL file does not exist: {input_path}")

    engine = create_engine(database_url)
    try:
        async with engine.begin() as connection:
            if truncate:
                table_sql = ", ".join(f'"{table}"' for table in TRUNCATE_TABLES)
                print("Truncating Fanora demo tables with CASCADE")
                await connection.execute(text(f"TRUNCATE TABLE {table_sql} RESTART IDENTITY CASCADE"))

            statements = split_sql_statements(input_path.read_text(encoding="utf-8"))
            written = 0
            for statement in statements:
                if statement.startswith("--"):
                    continue
                try:
                    await connection.execute(text(statement))
                    written += 1
                except SQLAlchemyError as error:
                    if not continue_on_error:
                        raise
                    first_line = statement.splitlines()[0][:160]
                    print(f"Warning: skipped statement: {first_line}")
                    print(f"Reason: {error.__class__.__name__}: {error}")
            print(f"Import completed: executed_statements={written}")
    finally:
        await engine.dispose()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--database-url",
        default=os.getenv("DATABASE_URL") or settings.database_url,
        help="Target database URL, defaults to DATABASE_URL",
    )
    parser.add_argument("--input", default=DEFAULT_INPUT, help=f"Input SQL file, default: {DEFAULT_INPUT}")
    parser.add_argument("--no-truncate", action="store_true", help="Do not truncate tables before import")
    parser.add_argument("--continue-on-error", action="store_true", help="Warn and continue on failed statements")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    asyncio.run(
        import_sql(
            args.database_url,
            Path(args.input),
            truncate=not args.no_truncate,
            continue_on_error=args.continue_on_error,
        )
    )
