"""Clear all business tables, then import SQL generated by export_demo_data_sql.py."""

import argparse
import asyncio
import os
import re
import sys
from pathlib import Path

from sqlalchemy import MetaData, Table, text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncConnection, AsyncEngine, create_async_engine

BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

from app.core.config import settings  # noqa: E402

DEFAULT_INPUT = BACKEND_ROOT / "fanora_demo_data.sql"
EXCLUDED_TABLES = {"alembic_version"}


def async_database_url(url: str) -> str:
    if url.startswith("postgres://"):
        return url.replace("postgres://", "postgresql+psycopg://", 1)
    if url.startswith("postgresql://"):
        return url.replace("postgresql://", "postgresql+psycopg://", 1)
    if url.startswith("sqlite://") and not url.startswith("sqlite+aiosqlite://"):
        return url.replace("sqlite://", "sqlite+aiosqlite://", 1)
    return url


def create_engine(url: str) -> AsyncEngine:
    normalized_url = async_database_url(url)
    options = (
        {} if normalized_url.startswith("sqlite") else {"pool_pre_ping": True, "connect_args": {"connect_timeout": 30}}
    )
    return create_async_engine(normalized_url, **options)


def sql_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


async def reflect_tables(engine: AsyncEngine) -> list[Table]:
    metadata = MetaData()
    async with engine.connect() as connection:
        await connection.run_sync(metadata.reflect)
    return [table for table in metadata.sorted_tables if table.name not in EXCLUDED_TABLES]


def strip_sql_comments(sql: str) -> str:
    return "\n".join(line for line in sql.splitlines() if not line.lstrip().startswith("--"))


def split_sql_statements(sql: str) -> list[str]:
    statements: list[str] = []
    current: list[str] = []
    in_quote = False
    cleaned_sql = strip_sql_comments(sql)
    index = 0
    while index < len(cleaned_sql):
        char = cleaned_sql[index]
        current.append(char)
        if char == "'":
            if in_quote and index + 1 < len(cleaned_sql) and cleaned_sql[index + 1] == "'":
                current.append(cleaned_sql[index + 1])
                index += 2
                continue
            in_quote = not in_quote
        elif char == ";" and not in_quote:
            statement = "".join(current).strip()
            if statement:
                statements.append(statement)
            current = []
        index += 1
    tail = "".join(current).strip()
    if tail:
        statements.append(tail)
    return statements


def statement_table_name(statement: str) -> str | None:
    match = re.match(r'INSERT\s+INTO\s+"?([A-Za-z_][A-Za-z0-9_]*)"?', statement, flags=re.IGNORECASE)
    return match.group(1) if match else None


async def clear_business_tables(connection: AsyncConnection, tables: list[Table]) -> None:
    if not tables:
        return
    if connection.dialect.name == "postgresql":
        table_sql = ", ".join(sql_identifier(table.name) for table in tables)
        await connection.execute(text(f"TRUNCATE TABLE {table_sql} RESTART IDENTITY CASCADE"))
        return

    for table in reversed(tables):
        await connection.execute(text(f"DELETE FROM {sql_identifier(table.name)}"))


async def import_sql(
    database_url: str,
    input_path: Path,
    *,
    continue_on_error: bool = False,
) -> None:
    if not input_path.exists():
        raise FileNotFoundError(f"SQL file does not exist: {input_path}")

    statements = split_sql_statements(input_path.read_text(encoding="utf-8"))
    invalid_tables = sorted(
        {
            table_name
            for statement in statements
            if (table_name := statement_table_name(statement)) in EXCLUDED_TABLES
        }
    )
    if invalid_tables:
        raise ValueError(f"Import file must not contain excluded tables: {', '.join(invalid_tables)}")

    engine = create_engine(database_url)
    try:
        tables = await reflect_tables(engine)
        target_table_names = {table.name for table in tables}
        unknown_tables = sorted(
            {
                table_name
                for statement in statements
                if (table_name := statement_table_name(statement)) is not None
                and table_name not in target_table_names
            }
        )
        if unknown_tables:
            raise ValueError(f"Import file contains tables missing from target database: {', '.join(unknown_tables)}")

        async with engine.begin() as connection:
            print(f"Clearing {len(tables)} business tables before import")
            await clear_business_tables(connection, tables)

            written = 0
            skipped = 0
            for statement in statements:
                if statement_table_name(statement) is None:
                    continue
                try:
                    if continue_on_error:
                        async with connection.begin_nested():
                            await connection.exec_driver_sql(statement)
                    else:
                        await connection.exec_driver_sql(statement)
                    written += 1
                except SQLAlchemyError as error:
                    if not continue_on_error:
                        raise
                    skipped += 1
                    first_line = statement.splitlines()[0][:160]
                    print(f"Warning: skipped statement: {first_line}")
                    print(f"Reason: {error.__class__.__name__}: {error}")
            print(f"Import completed: tables_cleared={len(tables)}, rows_inserted={written}, rows_skipped={skipped}")
    finally:
        await engine.dispose()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--database-url",
        default=os.getenv("DATABASE_URL") or settings.database_url,
        help="Target database URL, defaults to DATABASE_URL",
    )
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help=f"Input SQL file, default: {DEFAULT_INPUT}")
    parser.add_argument("--continue-on-error", action="store_true", help="Skip invalid rows using savepoints")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    asyncio.run(import_sql(args.database_url, Path(args.input), continue_on_error=args.continue_on_error))
