"""Fanora V1 schema baseline for fresh PostgreSQL deployments.

Historical pre-V1 migrations are retained in ``alembic/legacy_versions`` for audit
and existing-database adoption only.
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = "20260723_v1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collectible_token_types',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('metadata_cid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('max_supply', sa.BigInteger(), nullable=False),
    sa.Column('minted_supply', sa.BigInteger(), nullable=False),
    sa.Column('per_wallet_limit', sa.BigInteger(), nullable=False),
    sa.Column('mint_start', sa.DateTime(), nullable=False),
    sa.Column('mint_end', sa.DateTime(), nullable=False),
    sa.Column('transferable', sa.Boolean(), nullable=False),
    sa.Column('metadata_frozen', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_supply > 0', name='ck_collectible_max_supply_positive'),
    sa.CheckConstraint('per_wallet_limit > 0', name='ck_collectible_wallet_limit_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'contract_address', 'token_id', name='uq_collectible_token_type')
    )
    op.create_index(op.f('ix_collectible_token_types_active'), 'collectible_token_types', ['active'], unique=False)
    op.create_index(op.f('ix_collectible_token_types_category'), 'collectible_token_types', ['category'], unique=False)
    op.create_index(op.f('ix_collectible_token_types_chain_id'), 'collectible_token_types', ['chain_id'], unique=False)
    op.create_index(op.f('ix_collectible_token_types_contract_address'), 'collectible_token_types', ['contract_address'], unique=False)
    op.create_index(op.f('ix_collectible_token_types_source_id'), 'collectible_token_types', ['source_id'], unique=False)
    op.create_index(op.f('ix_collectible_token_types_status'), 'collectible_token_types', ['status'], unique=False)
    op.create_index(op.f('ix_collectible_token_types_token_id'), 'collectible_token_types', ['token_id'], unique=False)
    op.create_table('fan_token_config',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('icon_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_onchain', sa.Boolean(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('contract_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('decimals >= 0 AND decimals <= 18', name='ck_fan_token_config_decimals'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fan_token_rules',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('token_delta', sa.Integer(), nullable=False),
    sa.Column('verification_method', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('repeat_policy', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_limit', sa.Integer(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('daily_limit IS NULL OR daily_limit > 0', name='ck_fan_token_rule_daily_limit'),
    sa.CheckConstraint('monthly_limit IS NULL OR monthly_limit > 0', name='ck_fan_token_rule_monthly_limit'),
    sa.CheckConstraint('token_delta <> 0', name='ck_fan_token_rule_nonzero_delta'),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('sort_order', name='uq_fan_token_rule_sort_order')
    )
    op.create_index(op.f('ix_fan_token_rules_category'), 'fan_token_rules', ['category'], unique=False)
    op.create_index(op.f('ix_fan_token_rules_is_active'), 'fan_token_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_fan_token_rules_name'), 'fan_token_rules', ['name'], unique=False)
    op.create_index(op.f('ix_fan_token_rules_requires_review'), 'fan_token_rules', ['requires_review'], unique=False)
    op.create_index(op.f('ix_fan_token_rules_sort_order'), 'fan_token_rules', ['sort_order'], unique=False)
    op.create_table('login_challenges',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_challenges_expires_at'), 'login_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_login_challenges_wallet_address'), 'login_challenges', ['wallet_address'], unique=False)
    op.create_table('membership_levels',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('min_token_balance', sa.Integer(), nullable=True),
    sa.Column('max_token_balance', sa.Integer(), nullable=True),
    sa.Column('badge_image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('badge_image_cid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('badge_image_pin_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('badge_image_content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('is_management', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(is_management AND min_token_balance IS NULL AND max_token_balance IS NULL) OR (NOT is_management AND min_token_balance IS NOT NULL)', name='ck_membership_level_token_range'),
    sa.CheckConstraint('max_token_balance IS NULL OR min_token_balance IS NULL OR max_token_balance >= min_token_balance', name='ck_membership_level_max_token_balance'),
    sa.CheckConstraint('rank > 0', name='ck_membership_level_rank_positive'),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name', name='uq_membership_level_name'),
    sa.UniqueConstraint('rank', name='uq_membership_level_rank')
    )
    op.create_index(op.f('ix_membership_levels_is_active'), 'membership_levels', ['is_active'], unique=False)
    op.create_index(op.f('ix_membership_levels_is_management'), 'membership_levels', ['is_management'], unique=False)
    op.create_index(op.f('ix_membership_levels_min_token_balance'), 'membership_levels', ['min_token_balance'], unique=False)
    op.create_index(op.f('ix_membership_levels_name'), 'membership_levels', ['name'], unique=False)
    op.create_index(op.f('ix_membership_levels_rank'), 'membership_levels', ['rank'], unique=False)
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('auth_identities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_auth_identity_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('auth_security_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=True),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_security_events_created_at'), 'auth_security_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_security_events_event'), 'auth_security_events', ['event'], unique=False)
    op.create_index(op.f('ix_auth_security_events_outcome'), 'auth_security_events', ['outcome'], unique=False)
    op.create_index(op.f('ix_auth_security_events_user_id'), 'auth_security_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_auth_security_events_wallet_address'), 'auth_security_events', ['wallet_address'], unique=False)
    op.create_table('chain_operations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operation_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('operation_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('token_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata_cid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('transaction_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_chain_operation_idempotency_key')
    )
    op.create_index(op.f('ix_chain_operations_chain_id'), 'chain_operations', ['chain_id'], unique=False)
    op.create_index(op.f('ix_chain_operations_contract_address'), 'chain_operations', ['contract_address'], unique=False)
    op.create_index(op.f('ix_chain_operations_idempotency_key'), 'chain_operations', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_chain_operations_operation_hash'), 'chain_operations', ['operation_hash'], unique=True)
    op.create_index(op.f('ix_chain_operations_operation_type'), 'chain_operations', ['operation_type'], unique=False)
    op.create_index(op.f('ix_chain_operations_status'), 'chain_operations', ['status'], unique=False)
    op.create_index(op.f('ix_chain_operations_transaction_hash'), 'chain_operations', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_chain_operations_user_id'), 'chain_operations', ['user_id'], unique=False)
    op.create_table('communities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_is_public'), 'communities', ['is_public'], unique=False)
    op.create_index(op.f('ix_communities_name'), 'communities', ['name'], unique=False)
    op.create_index(op.f('ix_communities_owner_user_id'), 'communities', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_communities_slug'), 'communities', ['slug'], unique=True)
    op.create_table('daily_check_ins',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('reward_fan_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'check_in_date', name='uq_daily_check_in_user_date')
    )
    op.create_index(op.f('ix_daily_check_ins_check_in_date'), 'daily_check_ins', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_daily_check_ins_created_at'), 'daily_check_ins', ['created_at'], unique=False)
    op.create_index(op.f('ix_daily_check_ins_user_id'), 'daily_check_ins', ['user_id'], unique=False)
    op.create_table('fan_profile_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('community_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=False),
    sa.Column('analysis_source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('rule_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fan_profile_runs_analysis_source'), 'fan_profile_runs', ['analysis_source'], unique=False)
    op.create_index(op.f('ix_fan_profile_runs_community_id'), 'fan_profile_runs', ['community_id'], unique=False)
    op.create_index(op.f('ix_fan_profile_runs_degraded'), 'fan_profile_runs', ['degraded'], unique=False)
    op.create_index(op.f('ix_fan_profile_runs_user_id'), 'fan_profile_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_fan_profile_runs_wallet_address'), 'fan_profile_runs', ['wallet_address'], unique=False)
    op.create_table('nft_metadata_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('image_cid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('image_pin_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('metadata_cid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('metadata_pin_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('pin_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_id', 'version', name='uq_nft_metadata_version')
    )
    op.create_index(op.f('ix_nft_metadata_versions_created_by_user_id'), 'nft_metadata_versions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_nft_metadata_versions_metadata_cid'), 'nft_metadata_versions', ['metadata_cid'], unique=False)
    op.create_index(op.f('ix_nft_metadata_versions_pin_status'), 'nft_metadata_versions', ['pin_status'], unique=False)
    op.create_index(op.f('ix_nft_metadata_versions_subject_id'), 'nft_metadata_versions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_nft_metadata_versions_subject_type'), 'nft_metadata_versions', ['subject_type'], unique=False)
    op.create_table('official_membership_payments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('treasury_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('transaction_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('amount_wei', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount_wei >= 0', name='ck_official_membership_payment_amount_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_hash', name='uq_official_membership_payment_transaction'),
    sa.UniqueConstraint('user_id', name='uq_official_membership_payment_user')
    )
    op.create_index(op.f('ix_official_membership_payments_chain_id'), 'official_membership_payments', ['chain_id'], unique=False)
    op.create_index(op.f('ix_official_membership_payments_status'), 'official_membership_payments', ['status'], unique=False)
    op.create_index(op.f('ix_official_membership_payments_transaction_hash'), 'official_membership_payments', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_official_membership_payments_user_id'), 'official_membership_payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_official_membership_payments_wallet_address'), 'official_membership_payments', ['wallet_address'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=1500000), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=280), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('fan_token_balance', sa.Integer(), nullable=False),
    sa.Column('fan_token_lifetime_earned', sa.Integer(), nullable=False),
    sa.Column('fan_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('profile_visibility', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('is_official_member', sa.Boolean(), nullable=False),
    sa.Column('official_member_since', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_is_official_member'), 'user_profiles', ['is_official_member'], unique=False)
    op.create_index(op.f('ix_user_profiles_username'), 'user_profiles', ['username'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_role'), 'user_roles', ['role'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('wallet_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('chain_family', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=True)
    op.create_index(op.f('ix_wallets_is_primary'), 'wallets', ['is_primary'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('collectible_ownerships',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('claim_key', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('chain_operation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('minted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chain_operation_id'], ['chain_operations.id'], ),
    sa.ForeignKeyConstraint(['token_type_id'], ['collectible_token_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_type_id', 'user_id', name='uq_collectible_ownership')
    )
    op.create_index(op.f('ix_collectible_ownerships_claim_key'), 'collectible_ownerships', ['claim_key'], unique=True)
    op.create_index(op.f('ix_collectible_ownerships_status'), 'collectible_ownerships', ['status'], unique=False)
    op.create_index(op.f('ix_collectible_ownerships_token_type_id'), 'collectible_ownerships', ['token_type_id'], unique=False)
    op.create_index(op.f('ix_collectible_ownerships_user_id'), 'collectible_ownerships', ['user_id'], unique=False)
    op.create_index(op.f('ix_collectible_ownerships_wallet_address'), 'collectible_ownerships', ['wallet_address'], unique=False)
    op.create_table('community_members',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('community_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'user_id', name='uq_community_member')
    )
    op.create_index(op.f('ix_community_members_community_id'), 'community_members', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_members_user_id'), 'community_members', ['user_id'], unique=False)
    op.create_table('membership_identity_nfts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('token_id', sa.BigInteger(), nullable=True),
    sa.Column('level_id', sa.BigInteger(), nullable=False),
    sa.Column('level_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('metadata_version', sa.Integer(), nullable=False),
    sa.Column('metadata_cid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_member_card', sa.Boolean(), nullable=False),
    sa.Column('card_level_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('card_content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('card_fee_fan_tokens', sa.Integer(), nullable=False),
    sa.Column('card_created_at', sa.DateTime(), nullable=True),
    sa.Column('card_updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('chain_operation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('minted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chain_operation_id'], ['chain_operations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'contract_address', 'token_id', name='uq_membership_identity_token'),
    sa.UniqueConstraint('user_id', name='uq_membership_identity_user')
    )
    op.create_index(op.f('ix_membership_identity_nfts_chain_id'), 'membership_identity_nfts', ['chain_id'], unique=False)
    op.create_index(op.f('ix_membership_identity_nfts_contract_address'), 'membership_identity_nfts', ['contract_address'], unique=False)
    op.create_index(op.f('ix_membership_identity_nfts_is_member_card'), 'membership_identity_nfts', ['is_member_card'], unique=False)
    op.create_index(op.f('ix_membership_identity_nfts_status'), 'membership_identity_nfts', ['status'], unique=False)
    op.create_index(op.f('ix_membership_identity_nfts_user_id'), 'membership_identity_nfts', ['user_id'], unique=False)
    op.create_index(op.f('ix_membership_identity_nfts_wallet_address'), 'membership_identity_nfts', ['wallet_address'], unique=False)
    op.create_table('nft_applications',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('story_image_urls', sa.JSON(), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('public_attributes', sa.JSON(), nullable=False),
    sa.Column('copyright_declaration', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('price_fan_tokens', sa.BigInteger(), nullable=False),
    sa.Column('max_supply', sa.BigInteger(), nullable=False),
    sa.Column('publish_fee_fan_tokens', sa.BigInteger(), nullable=False),
    sa.Column('image_data', sqlmodel.sql.sqltypes.AutoString(length=7000000), nullable=True),
    sa.Column('image_mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('image_size_bytes', sa.Integer(), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('internal_review_note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('metadata_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('collectible_token_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_by_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collectible_token_type_id'], ['collectible_token_types.id'], ),
    sa.ForeignKeyConstraint(['metadata_version_id'], ['nft_metadata_versions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nft_applications_status'), 'nft_applications', ['status'], unique=False)
    op.create_index(op.f('ix_nft_applications_user_id'), 'nft_applications', ['user_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('community_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('cover_url', sqlmodel.sql.sqltypes.AutoString(length=1500000), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=False),
    sa.Column('linked_nft_creation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['linked_nft_creation_id'], ['nft_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_author_user_id'), 'community_posts', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_community_posts_category'), 'community_posts', ['category'], unique=False)
    op.create_index(op.f('ix_community_posts_community_id'), 'community_posts', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_posts_created_at'), 'community_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_linked_nft_creation_id'), 'community_posts', ['linked_nft_creation_id'], unique=False)
    op.create_index(op.f('ix_community_posts_status'), 'community_posts', ['status'], unique=False)
    op.create_index(op.f('ix_community_posts_title'), 'community_posts', ['title'], unique=False)
    op.create_table('nft_creation_reactions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('application_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('favorited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['nft_applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'user_id', name='uq_nft_creation_reaction_user')
    )
    op.create_index(op.f('ix_nft_creation_reactions_application_id'), 'nft_creation_reactions', ['application_id'], unique=False)
    op.create_index(op.f('ix_nft_creation_reactions_favorited'), 'nft_creation_reactions', ['favorited'], unique=False)
    op.create_index(op.f('ix_nft_creation_reactions_liked'), 'nft_creation_reactions', ['liked'], unique=False)
    op.create_index(op.f('ix_nft_creation_reactions_user_id'), 'nft_creation_reactions', ['user_id'], unique=False)
    op.create_table('community_post_reactions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('bookmarked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_community_post_reaction_user')
    )
    op.create_index(op.f('ix_community_post_reactions_bookmarked'), 'community_post_reactions', ['bookmarked'], unique=False)
    op.create_index(op.f('ix_community_post_reactions_liked'), 'community_post_reactions', ['liked'], unique=False)
    op.create_index(op.f('ix_community_post_reactions_post_id'), 'community_post_reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_post_reactions_user_id'), 'community_post_reactions', ['user_id'], unique=False)
    op.create_table('community_replies',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_reply_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('image_urls', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_reply_id'], ['community_replies.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_replies_author_user_id'), 'community_replies', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_community_replies_created_at'), 'community_replies', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_replies_parent_reply_id'), 'community_replies', ['parent_reply_id'], unique=False)
    op.create_index(op.f('ix_community_replies_post_id'), 'community_replies', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_replies_status'), 'community_replies', ['status'], unique=False)
    op.create_table('fan_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('community_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('reward_fan_tokens', sa.Integer(), nullable=False),
    sa.Column('target_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validation_rule', sa.JSON(), nullable=False),
    sa.Column('participation_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('participation_limit IS NULL OR participation_limit > 0', name='ck_fan_tasks_participation_limit'),
    sa.CheckConstraint('reward_fan_tokens > 0', name='ck_fan_tasks_positive_reward'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_post_id'], ['community_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fan_tasks_community_id'), 'fan_tasks', ['community_id'], unique=False)
    op.create_index(op.f('ix_fan_tasks_created_at'), 'fan_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_fan_tasks_created_by_user_id'), 'fan_tasks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_fan_tasks_end_at'), 'fan_tasks', ['end_at'], unique=False)
    op.create_index(op.f('ix_fan_tasks_start_at'), 'fan_tasks', ['start_at'], unique=False)
    op.create_index(op.f('ix_fan_tasks_status'), 'fan_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_fan_tasks_target_post_id'), 'fan_tasks', ['target_post_id'], unique=False)
    op.create_index(op.f('ix_fan_tasks_task_type'), 'fan_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_fan_tasks_title'), 'fan_tasks', ['title'], unique=False)
    op.create_table('community_reply_likes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reply_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['community_replies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reply_id', 'user_id', name='uq_community_reply_like_user')
    )
    op.create_index(op.f('ix_community_reply_likes_reply_id'), 'community_reply_likes', ['reply_id'], unique=False)
    op.create_index(op.f('ix_community_reply_likes_user_id'), 'community_reply_likes', ['user_id'], unique=False)
    op.create_table('fan_token_ledger',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('balance_after >= 0', name='ck_fan_token_ledger_nonnegative_balance'),
    sa.CheckConstraint('delta <> 0', name='ck_fan_token_ledger_nonzero_delta'),
    sa.ForeignKeyConstraint(['task_id'], ['fan_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_fan_token_ledger_idempotency_key')
    )
    op.create_index(op.f('ix_fan_token_ledger_created_at'), 'fan_token_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_fan_token_ledger_idempotency_key'), 'fan_token_ledger', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_fan_token_ledger_source_id'), 'fan_token_ledger', ['source_id'], unique=False)
    op.create_index(op.f('ix_fan_token_ledger_source_type'), 'fan_token_ledger', ['source_type'], unique=False)
    op.create_index(op.f('ix_fan_token_ledger_task_id'), 'fan_token_ledger', ['task_id'], unique=False)
    op.create_index(op.f('ix_fan_token_ledger_user_id'), 'fan_token_ledger', ['user_id'], unique=False)
    op.create_table('task_participations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('reward_snapshot', sa.Integer(), nullable=False),
    sa.Column('reply_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submission', sa.JSON(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['community_replies.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['fan_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', name='uq_task_participation_user')
    )
    op.create_index(op.f('ix_task_participations_reply_id'), 'task_participations', ['reply_id'], unique=False)
    op.create_index(op.f('ix_task_participations_status'), 'task_participations', ['status'], unique=False)
    op.create_index(op.f('ix_task_participations_task_id'), 'task_participations', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_participations_user_id'), 'task_participations', ['user_id'], unique=False)
    op.create_table('task_audit_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participation_id'], ['task_participations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['fan_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_audit_logs_actor_user_id'), 'task_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_task_audit_logs_created_at'), 'task_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_audit_logs_event'), 'task_audit_logs', ['event'], unique=False)
    op.create_index(op.f('ix_task_audit_logs_participation_id'), 'task_audit_logs', ['participation_id'], unique=False)
    op.create_index(op.f('ix_task_audit_logs_task_id'), 'task_audit_logs', ['task_id'], unique=False)
    op.create_table('task_content_reviews',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('review_source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('rule_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participation_id'], ['task_participations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['fan_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_content_reviews_created_at'), 'task_content_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_content_reviews_decision'), 'task_content_reviews', ['decision'], unique=False)
    op.create_index(op.f('ix_task_content_reviews_degraded'), 'task_content_reviews', ['degraded'], unique=False)
    op.create_index(op.f('ix_task_content_reviews_participation_id'), 'task_content_reviews', ['participation_id'], unique=False)
    op.create_index(op.f('ix_task_content_reviews_review_source'), 'task_content_reviews', ['review_source'], unique=False)
    op.create_index(op.f('ix_task_content_reviews_source_id'), 'task_content_reviews', ['source_id'], unique=False)
    op.create_index(op.f('ix_task_content_reviews_source_type'), 'task_content_reviews', ['source_type'], unique=False)
    op.create_index(op.f('ix_task_content_reviews_task_id'), 'task_content_reviews', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_content_reviews_user_id'), 'task_content_reviews', ['user_id'], unique=False)
    op.create_table('task_nft_rewards',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reward_version', sa.Integer(), nullable=False),
    sa.Column('token_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ownership_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ownership_id'], ['collectible_ownerships.id'], ),
    sa.ForeignKeyConstraint(['participation_id'], ['task_participations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['fan_tasks.id'], ),
    sa.ForeignKeyConstraint(['token_type_id'], ['collectible_token_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participation_id', 'reward_version', name='uq_task_nft_reward_participation_version'),
    sa.UniqueConstraint('task_id', 'user_id', 'reward_version', name='uq_task_nft_reward_user_version')
    )
    op.create_index(op.f('ix_task_nft_rewards_ownership_id'), 'task_nft_rewards', ['ownership_id'], unique=False)
    op.create_index(op.f('ix_task_nft_rewards_participation_id'), 'task_nft_rewards', ['participation_id'], unique=False)
    op.create_index(op.f('ix_task_nft_rewards_status'), 'task_nft_rewards', ['status'], unique=False)
    op.create_index(op.f('ix_task_nft_rewards_task_id'), 'task_nft_rewards', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_nft_rewards_token_type_id'), 'task_nft_rewards', ['token_type_id'], unique=False)
    op.create_index(op.f('ix_task_nft_rewards_user_id'), 'task_nft_rewards', ['user_id'], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION fanora_sync_membership_level() RETURNS trigger AS $$
            DECLARE
                computed_level varchar(30);
            BEGIN
                IF NEW.level = '神经领袖' THEN
                    RETURN NEW;
                END IF;
                SELECT membership_levels.name INTO computed_level
                FROM membership_levels
                WHERE membership_levels.is_active = true
                  AND membership_levels.is_management = false
                  AND NEW.fan_token_lifetime_earned >= membership_levels.min_token_balance
                  AND (membership_levels.max_token_balance IS NULL
                       OR NEW.fan_token_lifetime_earned <= membership_levels.max_token_balance)
                ORDER BY membership_levels.rank DESC
                LIMIT 1;
                NEW.level := COALESCE(computed_level, '新生儿');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER trg_user_profiles_sync_membership_level
            BEFORE INSERT OR UPDATE OF fan_token_lifetime_earned ON user_profiles
            FOR EACH ROW EXECUTE FUNCTION fanora_sync_membership_level();
            """
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS trg_user_profiles_sync_membership_level ON user_profiles")
        op.execute("DROP FUNCTION IF EXISTS fanora_sync_membership_level()")
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_nft_rewards_user_id'), table_name='task_nft_rewards')
    op.drop_index(op.f('ix_task_nft_rewards_token_type_id'), table_name='task_nft_rewards')
    op.drop_index(op.f('ix_task_nft_rewards_task_id'), table_name='task_nft_rewards')
    op.drop_index(op.f('ix_task_nft_rewards_status'), table_name='task_nft_rewards')
    op.drop_index(op.f('ix_task_nft_rewards_participation_id'), table_name='task_nft_rewards')
    op.drop_index(op.f('ix_task_nft_rewards_ownership_id'), table_name='task_nft_rewards')
    op.drop_table('task_nft_rewards')
    op.drop_index(op.f('ix_task_content_reviews_user_id'), table_name='task_content_reviews')
    op.drop_index(op.f('ix_task_content_reviews_task_id'), table_name='task_content_reviews')
    op.drop_index(op.f('ix_task_content_reviews_source_type'), table_name='task_content_reviews')
    op.drop_index(op.f('ix_task_content_reviews_source_id'), table_name='task_content_reviews')
    op.drop_index(op.f('ix_task_content_reviews_review_source'), table_name='task_content_reviews')
    op.drop_index(op.f('ix_task_content_reviews_participation_id'), table_name='task_content_reviews')
    op.drop_index(op.f('ix_task_content_reviews_degraded'), table_name='task_content_reviews')
    op.drop_index(op.f('ix_task_content_reviews_decision'), table_name='task_content_reviews')
    op.drop_index(op.f('ix_task_content_reviews_created_at'), table_name='task_content_reviews')
    op.drop_table('task_content_reviews')
    op.drop_index(op.f('ix_task_audit_logs_task_id'), table_name='task_audit_logs')
    op.drop_index(op.f('ix_task_audit_logs_participation_id'), table_name='task_audit_logs')
    op.drop_index(op.f('ix_task_audit_logs_event'), table_name='task_audit_logs')
    op.drop_index(op.f('ix_task_audit_logs_created_at'), table_name='task_audit_logs')
    op.drop_index(op.f('ix_task_audit_logs_actor_user_id'), table_name='task_audit_logs')
    op.drop_table('task_audit_logs')
    op.drop_index(op.f('ix_task_participations_user_id'), table_name='task_participations')
    op.drop_index(op.f('ix_task_participations_task_id'), table_name='task_participations')
    op.drop_index(op.f('ix_task_participations_status'), table_name='task_participations')
    op.drop_index(op.f('ix_task_participations_reply_id'), table_name='task_participations')
    op.drop_table('task_participations')
    op.drop_index(op.f('ix_fan_token_ledger_user_id'), table_name='fan_token_ledger')
    op.drop_index(op.f('ix_fan_token_ledger_task_id'), table_name='fan_token_ledger')
    op.drop_index(op.f('ix_fan_token_ledger_source_type'), table_name='fan_token_ledger')
    op.drop_index(op.f('ix_fan_token_ledger_source_id'), table_name='fan_token_ledger')
    op.drop_index(op.f('ix_fan_token_ledger_idempotency_key'), table_name='fan_token_ledger')
    op.drop_index(op.f('ix_fan_token_ledger_created_at'), table_name='fan_token_ledger')
    op.drop_table('fan_token_ledger')
    op.drop_index(op.f('ix_community_reply_likes_user_id'), table_name='community_reply_likes')
    op.drop_index(op.f('ix_community_reply_likes_reply_id'), table_name='community_reply_likes')
    op.drop_table('community_reply_likes')
    op.drop_index(op.f('ix_fan_tasks_title'), table_name='fan_tasks')
    op.drop_index(op.f('ix_fan_tasks_task_type'), table_name='fan_tasks')
    op.drop_index(op.f('ix_fan_tasks_target_post_id'), table_name='fan_tasks')
    op.drop_index(op.f('ix_fan_tasks_status'), table_name='fan_tasks')
    op.drop_index(op.f('ix_fan_tasks_start_at'), table_name='fan_tasks')
    op.drop_index(op.f('ix_fan_tasks_end_at'), table_name='fan_tasks')
    op.drop_index(op.f('ix_fan_tasks_created_by_user_id'), table_name='fan_tasks')
    op.drop_index(op.f('ix_fan_tasks_created_at'), table_name='fan_tasks')
    op.drop_index(op.f('ix_fan_tasks_community_id'), table_name='fan_tasks')
    op.drop_table('fan_tasks')
    op.drop_index(op.f('ix_community_replies_status'), table_name='community_replies')
    op.drop_index(op.f('ix_community_replies_post_id'), table_name='community_replies')
    op.drop_index(op.f('ix_community_replies_parent_reply_id'), table_name='community_replies')
    op.drop_index(op.f('ix_community_replies_created_at'), table_name='community_replies')
    op.drop_index(op.f('ix_community_replies_author_user_id'), table_name='community_replies')
    op.drop_table('community_replies')
    op.drop_index(op.f('ix_community_post_reactions_user_id'), table_name='community_post_reactions')
    op.drop_index(op.f('ix_community_post_reactions_post_id'), table_name='community_post_reactions')
    op.drop_index(op.f('ix_community_post_reactions_liked'), table_name='community_post_reactions')
    op.drop_index(op.f('ix_community_post_reactions_bookmarked'), table_name='community_post_reactions')
    op.drop_table('community_post_reactions')
    op.drop_index(op.f('ix_nft_creation_reactions_user_id'), table_name='nft_creation_reactions')
    op.drop_index(op.f('ix_nft_creation_reactions_liked'), table_name='nft_creation_reactions')
    op.drop_index(op.f('ix_nft_creation_reactions_favorited'), table_name='nft_creation_reactions')
    op.drop_index(op.f('ix_nft_creation_reactions_application_id'), table_name='nft_creation_reactions')
    op.drop_table('nft_creation_reactions')
    op.drop_index(op.f('ix_community_posts_title'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_status'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_linked_nft_creation_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_created_at'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_community_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_category'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_user_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_nft_applications_user_id'), table_name='nft_applications')
    op.drop_index(op.f('ix_nft_applications_status'), table_name='nft_applications')
    op.drop_table('nft_applications')
    op.drop_index(op.f('ix_membership_identity_nfts_wallet_address'), table_name='membership_identity_nfts')
    op.drop_index(op.f('ix_membership_identity_nfts_user_id'), table_name='membership_identity_nfts')
    op.drop_index(op.f('ix_membership_identity_nfts_status'), table_name='membership_identity_nfts')
    op.drop_index(op.f('ix_membership_identity_nfts_is_member_card'), table_name='membership_identity_nfts')
    op.drop_index(op.f('ix_membership_identity_nfts_contract_address'), table_name='membership_identity_nfts')
    op.drop_index(op.f('ix_membership_identity_nfts_chain_id'), table_name='membership_identity_nfts')
    op.drop_table('membership_identity_nfts')
    op.drop_index(op.f('ix_community_members_user_id'), table_name='community_members')
    op.drop_index(op.f('ix_community_members_community_id'), table_name='community_members')
    op.drop_table('community_members')
    op.drop_index(op.f('ix_collectible_ownerships_wallet_address'), table_name='collectible_ownerships')
    op.drop_index(op.f('ix_collectible_ownerships_user_id'), table_name='collectible_ownerships')
    op.drop_index(op.f('ix_collectible_ownerships_token_type_id'), table_name='collectible_ownerships')
    op.drop_index(op.f('ix_collectible_ownerships_status'), table_name='collectible_ownerships')
    op.drop_index(op.f('ix_collectible_ownerships_claim_key'), table_name='collectible_ownerships')
    op.drop_table('collectible_ownerships')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_is_primary'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_profiles_username'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_is_official_member'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_official_membership_payments_wallet_address'), table_name='official_membership_payments')
    op.drop_index(op.f('ix_official_membership_payments_user_id'), table_name='official_membership_payments')
    op.drop_index(op.f('ix_official_membership_payments_transaction_hash'), table_name='official_membership_payments')
    op.drop_index(op.f('ix_official_membership_payments_status'), table_name='official_membership_payments')
    op.drop_index(op.f('ix_official_membership_payments_chain_id'), table_name='official_membership_payments')
    op.drop_table('official_membership_payments')
    op.drop_index(op.f('ix_nft_metadata_versions_subject_type'), table_name='nft_metadata_versions')
    op.drop_index(op.f('ix_nft_metadata_versions_subject_id'), table_name='nft_metadata_versions')
    op.drop_index(op.f('ix_nft_metadata_versions_pin_status'), table_name='nft_metadata_versions')
    op.drop_index(op.f('ix_nft_metadata_versions_metadata_cid'), table_name='nft_metadata_versions')
    op.drop_index(op.f('ix_nft_metadata_versions_created_by_user_id'), table_name='nft_metadata_versions')
    op.drop_table('nft_metadata_versions')
    op.drop_index(op.f('ix_fan_profile_runs_wallet_address'), table_name='fan_profile_runs')
    op.drop_index(op.f('ix_fan_profile_runs_user_id'), table_name='fan_profile_runs')
    op.drop_index(op.f('ix_fan_profile_runs_degraded'), table_name='fan_profile_runs')
    op.drop_index(op.f('ix_fan_profile_runs_community_id'), table_name='fan_profile_runs')
    op.drop_index(op.f('ix_fan_profile_runs_analysis_source'), table_name='fan_profile_runs')
    op.drop_table('fan_profile_runs')
    op.drop_index(op.f('ix_daily_check_ins_user_id'), table_name='daily_check_ins')
    op.drop_index(op.f('ix_daily_check_ins_created_at'), table_name='daily_check_ins')
    op.drop_index(op.f('ix_daily_check_ins_check_in_date'), table_name='daily_check_ins')
    op.drop_table('daily_check_ins')
    op.drop_index(op.f('ix_communities_slug'), table_name='communities')
    op.drop_index(op.f('ix_communities_owner_user_id'), table_name='communities')
    op.drop_index(op.f('ix_communities_name'), table_name='communities')
    op.drop_index(op.f('ix_communities_is_public'), table_name='communities')
    op.drop_table('communities')
    op.drop_index(op.f('ix_chain_operations_user_id'), table_name='chain_operations')
    op.drop_index(op.f('ix_chain_operations_transaction_hash'), table_name='chain_operations')
    op.drop_index(op.f('ix_chain_operations_status'), table_name='chain_operations')
    op.drop_index(op.f('ix_chain_operations_operation_type'), table_name='chain_operations')
    op.drop_index(op.f('ix_chain_operations_operation_hash'), table_name='chain_operations')
    op.drop_index(op.f('ix_chain_operations_idempotency_key'), table_name='chain_operations')
    op.drop_index(op.f('ix_chain_operations_contract_address'), table_name='chain_operations')
    op.drop_index(op.f('ix_chain_operations_chain_id'), table_name='chain_operations')
    op.drop_table('chain_operations')
    op.drop_index(op.f('ix_auth_security_events_wallet_address'), table_name='auth_security_events')
    op.drop_index(op.f('ix_auth_security_events_user_id'), table_name='auth_security_events')
    op.drop_index(op.f('ix_auth_security_events_outcome'), table_name='auth_security_events')
    op.drop_index(op.f('ix_auth_security_events_event'), table_name='auth_security_events')
    op.drop_index(op.f('ix_auth_security_events_created_at'), table_name='auth_security_events')
    op.drop_table('auth_security_events')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_membership_levels_rank'), table_name='membership_levels')
    op.drop_index(op.f('ix_membership_levels_name'), table_name='membership_levels')
    op.drop_index(op.f('ix_membership_levels_min_token_balance'), table_name='membership_levels')
    op.drop_index(op.f('ix_membership_levels_is_management'), table_name='membership_levels')
    op.drop_index(op.f('ix_membership_levels_is_active'), table_name='membership_levels')
    op.drop_table('membership_levels')
    op.drop_index(op.f('ix_login_challenges_wallet_address'), table_name='login_challenges')
    op.drop_index(op.f('ix_login_challenges_expires_at'), table_name='login_challenges')
    op.drop_table('login_challenges')
    op.drop_index(op.f('ix_fan_token_rules_sort_order'), table_name='fan_token_rules')
    op.drop_index(op.f('ix_fan_token_rules_requires_review'), table_name='fan_token_rules')
    op.drop_index(op.f('ix_fan_token_rules_name'), table_name='fan_token_rules')
    op.drop_index(op.f('ix_fan_token_rules_is_active'), table_name='fan_token_rules')
    op.drop_index(op.f('ix_fan_token_rules_category'), table_name='fan_token_rules')
    op.drop_table('fan_token_rules')
    op.drop_table('fan_token_config')
    op.drop_index(op.f('ix_collectible_token_types_token_id'), table_name='collectible_token_types')
    op.drop_index(op.f('ix_collectible_token_types_status'), table_name='collectible_token_types')
    op.drop_index(op.f('ix_collectible_token_types_source_id'), table_name='collectible_token_types')
    op.drop_index(op.f('ix_collectible_token_types_contract_address'), table_name='collectible_token_types')
    op.drop_index(op.f('ix_collectible_token_types_chain_id'), table_name='collectible_token_types')
    op.drop_index(op.f('ix_collectible_token_types_category'), table_name='collectible_token_types')
    op.drop_index(op.f('ix_collectible_token_types_active'), table_name='collectible_token_types')
    op.drop_table('collectible_token_types')
    # ### end Alembic commands ###